import Header from "../component/header/header";
import Footer from "../component/footer/footer";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Okinawa site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`bg-[#EEEDDD] ${geistSans.variable} ${geistMono.variable} antialiased`}>
      <Header/>
        <main className="pt-24">
          {children}
        </main>
      <Footer/>
      </body>
    </html>
  );
}
